### ISSUE TITLE
运行测试用例有错误

### ISSUE THREAD

**Issue by kohn** [shengbinmeng/ffmpeg-h264-dec#1]
解码test/352x288Foreman.264到83帧的时候出现错误提示:

[h264 @ 0x7f947b802000] slice type 32 too large at -1
[h264 @ 0x7f947b802000] decode_slice_header error
[h264 @ 0x7f947b802000] decode_slice_header error

虽然最后也生成了yuv文件, 但是我用ffmpeg想把yuv转换成wmv格式看看是否decode成功, 结果ffmpeg提示:
[IMGUTILS @ 0x7fff50cd5780] Picture size 0x0 is invalid
352x288Foreman.yuv: Invalid argument

能请教一下这是什么问题吗?

**Comment by shengbinmeng** [comment]
我试了下没有你说的问题。运行过程中报的信息只要不中断运行就不算错误。

你看你生成的yuv的文件大小是否正常？应为36495360字节。

另外，看上去可能是你yuv转wmv的命令不太对。

**Comment by kohn** [comment]
感谢回复! 仔细查阅了一下ffmpeg的命令, 发现确实是我转wmv的命令不对. 谢谢
