### ISSUE TITLE
Test files

### ISSUE THREAD

**Issue by ardhipoetra** [shengbinmeng/ffmpeg-h264-dec#10]
Hi, 

It seems I can't decode my other example raw h264. How did you create your test files?

Based on my quick debug, all my test case stuck in https://github.com/shengbinmeng/ffmpeg-h264-dec/blob/49ec2326a4a7e287db511c5c77c004941cc9d85a/main.c#L128

**Comment by shengbinmeng** [comment]
I extracted raw h264 files from MP4 files using FFmpeg, like this: `ffmpeg -i input.mp4 -c:v copy -an out.h264`.

**Comment by ardhipoetra** [comment]
That was helpful, thanks! 

Note that it still somehow not all mp4/mkv compatible with the decoder. Some gives me infinite loop.

Close the issue for now
