### ISSUE TITLE
Decoding h264 Stream

### ISSUE THREAD

**Issue by AmdEagle** [shengbinmeng/ffmpeg-h264-dec#2]
I have a h264 stream ( nal units )( uint8Array ) which i need to decode to yuv so i can display it on a html5 canvas.

How do i use your library to go about doing that?
Another problem i am encountering is that when i try to run emmake make h264dec.html i get the following error
![image](https://cloud.githubusercontent.com/assets/6722962/23151614/4d11d9fa-f837-11e6-86b8-0a1b6f32fe4c.png)

your help is greatly appreciated

**Comment by shengbinmeng** [comment]
About the error, it seems that you did not clean before running `emmake make`. As stated in the README file, "`make clean` is usually needed before building for another platform". Please clean everything and try again.

**Comment by shengbinmeng** [comment]
See <https://github.com/shengbinmeng/javascript-ts-player> for how the JavaScript decoder can be used in a web page.

**Comment by AmdEagle** [comment]
Thank you for the fast response

I tried running `make clean` before running `emmake  make` inside the javascript folder. But I am getting this error
![image](https://cloud.githubusercontent.com/assets/6722962/23153459/b6cfc954-f843-11e6-8f7d-c526b3f0c8f2.png)


I ran `make clean` in the main folder and then `emmake make h264dec.html` i am still getting an error
![image](https://cloud.githubusercontent.com/assets/6722962/23153523/182fe68e-f844-11e6-96c4-a70896b3cb2c.png)

**Comment by shengbinmeng** [comment]
What's your `emcc` version (output by `emcc -v`)?

If you install `emscripten` from Ubuntu's `apt-get`, the version may be too old. I just tried v1.35.0 (on macOS though), no error occurred.

**Comment by AmdEagle** [comment]
I am sorry i having no luck in this. Would you be able help me in uploading `decoder.js` version after building it using emscripten may be under release or build folder.I will be able to call it browser which would allow me to decode the h264 stream NAL Units that are being pumped from the websocket.

It would be great help to me would really appreciate it.

**Comment by shengbinmeng** [comment]
If you just want the result, you can get it from: <https://github.com/shengbinmeng/javascript-ts-player/tree/master/js>. The file `Decoder-ff.js` is what I built using emscripten.

**Comment by AmdEagle** [comment]
Thank you i tried the decoder-ff.js. But i this error on the console.
![image](https://cloud.githubusercontent.com/assets/6722962/23298353/515b59cc-fab8-11e6-86d7-48e4f8c14735.png)

Would you be able to help me out with this ?

**Comment by shengbinmeng** [comment]
Please try `demo-ff.html` in <https://github.com/shengbinmeng/javascript-ts-player>. Does it work? Or the same error?

**Comment by AmdEagle** [comment]
Demo works fine i tried it. But I am trying to play a raw .h264 file instead of a ts file

I am trying to play a h264 stream ( NAL Units ). So i was not able to use the `TSPlayer` so i extracted your player and wrote my code like this 
![image](https://cloud.githubusercontent.com/assets/6722962/23298745/cddc702a-fab9-11e6-8f3e-8d51e2680ff2.png)

then i pass in each h264 nal unit like this to the player 
`player.decode( h264_NAL_Unit );`

**Comment by shengbinmeng** [comment]
Try the attached version, which was built with `-s ALLOW_MEMORY_GROWTH=1`. 
[Decoder-allow-memory-growth.js.zip](https://github.com/shengbinmeng/ffmpeg-h264-dec/files/798919/Decoder-allow-memory-growth.js.zip)
