### ISSUE TITLE
compilation error __atomic_add_fetch()

### ISSUE THREAD

**Issue by kiran-raj94** [shengbinmeng/ffmpeg-h264-dec#4]
when i run  emmake make h264dec.node.js i get this error

./ffmpeg-src/libavutil/atomic_gcc.h:54:12: error: cannot compile this atomic library call yet
    return __atomic_add_fetch(ptr, inc, __ATOMIC_SEQ_CST);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
ERROR    root: compiler frontend failed to generate LLVM bitcode, halting
my clang version is 3.4

**Comment by shengbinmeng** [comment]
Please try emsdk-1.35.0 that comes with clang 3.7. (See the versions on bottom of this page: <http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html>)
