### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by JasonOldWoo** [shengbinmeng/ffmpeg-h264-dec#5]
按照README一步步来，提示
ERROR    root: h264dec.bc: No such file or directory ("h264dec.bc" was expected to be an input file, based on the commandline arguments provided)

**Comment by shengbinmeng** [comment]
是什么操作系统？我在macOS上试了下没问题。

**Comment by JasonOldWoo** [comment]
我是在ubuntu 18.04.2上。
可能macOS上默认编译器是clang，Linux可能需要修改下Makefile，等我自己再试试。
