### ISSUE TITLE
how to use h264dec.html

### ISSUE THREAD

**Issue by kiran-raj94** [shengbinmeng/ffmpeg-h264-dec#8]
Hi, I've generated h264dec.html file. I dont know how to play raw h264 in it. It says 
'Usage: ./this.program <input_file> <output_file>'
When i run the command, there is no response

**Comment by shengbinmeng** [comment]
I've added a note about that in the updated README.md: "Note that since we can not pass arguments to HTML pages, you should modify main.c (see the commented line in the main function) to let the program starts decoding without arguments."
